/*
Алгоритм действий:
  - Проход по всей структуре проекта и сбор всех пакетов и файлов.
  - Анализ комментариев и выявление структур с комментарием // generate:reset.
  - Генерация методов Reset() для найденных структур.
  - Запись результатов в файлы reset.gen.go внутри соответствующих пакетов.
*/
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const (
	generateComment = "// generate:reset"
	outputFileName  = "reset.gen.go"
)

func main() {
	// 1. Сканирование всех пакетов, начиная с корневой директории
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	packages := make(map[string]map[string]*ast.File) // map[dir]map[filename]*ast.File

	filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		// Пропускаем директории, которые обычно содержат сгенерированный код или тесты
		if strings.Contains(path, "/vendor/") {
			return filepath.SkipDir
		}

		fset := token.NewFileSet()
		pkgs, err := parser.ParseDir(fset, path, nil, parser.ParseComments)
		if err != nil {
			// Логируем ошибку, но продолжаем сканирование других директорий
			fmt.Printf("Warning: failed to parse directory %s: %v\n", path, err)
			return nil
		}

		for _, pkg := range pkgs {
			if packages[path] == nil {
				packages[path] = make(map[string]*ast.File)
			}
			for filename, file := range pkg.Files {
				packages[path][filename] = file
			}
		}
		return nil
	})

	// 2, 3 и 4: Поиск структур, генерация методов и запись в файлы
	for dir, files := range packages {
		structsToGenerate := make(map[string]*ast.TypeSpec)
		pkgName := ""

		for _, file := range files {
			if pkgName == "" {
				pkgName = file.Name.Name
			}
			ast.Inspect(file, func(n ast.Node) bool {
				genDecl, ok := n.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					return true
				}

				// Проверяем наличие комментария // generate:reset
				if genDecl.Doc != nil {
					for _, comment := range genDecl.Doc.List {
						if strings.Contains(comment.Text, generateComment) {
							for _, spec := range genDecl.Specs {
								typeSpec, ok := spec.(*ast.TypeSpec)
								if ok {
									if _, ok := typeSpec.Type.(*ast.StructType); ok {
										structsToGenerate[typeSpec.Name.Name] = typeSpec
									}
								}
							}
							break
						}
					}
				}
				return true
			})
		}

		if len(structsToGenerate) > 0 {
			if err := generateResetFile(dir, pkgName, structsToGenerate); err != nil {
				log.Printf("Error generating reset file for %s: %v\n", dir, err)
			}
		}
	}
}

// generateResetFile генерирует файл reset.gen.go для заданного пакета
func generateResetFile(dir, pkgName string, structs map[string]*ast.TypeSpec) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by reset tool. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	// Импорты, которые могут понадобиться (например, "clear" не требует импорта, интерфейс тоже)
	// Добавляем интерфейс Resetable для вложенных структур
	buf.WriteString("type resetable interface {\n\tReset()\n}\n\n")

	for structName, typeSpec := range structs {
		// Генерируем метод Reset()
		generateResetMethod(&buf, structName, typeSpec)
	}

	filePath := filepath.Join(dir, outputFileName)
	// Используем go/format для красивого вывода
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("Warning: failed to format generated code for %s: %v\n", dir, err)
		formatted = buf.Bytes() // Записываем неформатированный код, чтобы увидеть ошибку
	}
	return os.WriteFile(filePath, formatted, 0644)
}

// generateResetMethod генерирует тело метода Reset() для конкретной структуры
func generateResetMethod(buf *bytes.Buffer, structName string, typeSpec *ast.TypeSpec) {
	fmt.Fprintf(buf, "func (rs *%s) Reset() {\n", structName)
	fmt.Fprintf(buf, "\tif rs == nil {\n\t\treturn\n\t}\n\n")

	structType := typeSpec.Type.(*ast.StructType)
	for _, field := range structType.Fields.List {
		fieldName := field.Names[0].Name // Берем первое имя поля

		// Определяем тип поля для генерации соответствующего сброса
		switch t := field.Type.(type) {
		case *ast.Ident:
			// Примитивы (int, string, bool и т.д.)
			typeName := t.Name
			if isPrimitive(typeName) {
				fmt.Fprintf(buf, "\trs.%s = %s\n", fieldName, getZeroValue(typeName))
			} else {
				// Вложенные структуры без указателя (если имеют метод Reset)
				generateNestedStructReset(buf, fieldName)
			}

		case *ast.ArrayType:
			// Слайсы []T
			if t.Len == nil { // Это слайс, а не массив фиксированной длины
				fmt.Fprintf(buf, "\trs.%s = rs.%s[:0]\n", fieldName, fieldName)
			}

		case *ast.MapType:
			// Мапы map[K]V
			// Встроенная функция clear() доступна с Go 1.11+
			fmt.Fprintf(buf, "\tclear(rs.%s)\n", fieldName)

		case *ast.StarExpr:
			// Указатели *T
			// Проверяем, что указатель не nil, затем сбрасываем его значение
			fmt.Fprintf(buf, "\tif rs.%s != nil {\n", fieldName)
			// Определяем базовый тип указателя
			switch innerT := t.X.(type) {
			case *ast.Ident:
				innerTypeName := innerT.Name
				if isPrimitive(innerTypeName) {
					fmt.Fprintf(buf, "\t\t*rs.%s = %s\n", fieldName, getZeroValue(innerTypeName))
				} else {
					// Вложенный указатель на структуру (если имеет метод Reset)
					// Здесь логика сложнее: нам нужно убедиться, что базовый тип имеет метод Reset
					// Что уже покрыто генерируемым интерфейсом resetable
					generateNestedPointerReset(buf, fieldName)
				}
			case *ast.StarExpr, *ast.ArrayType, *ast.MapType, *ast.StructType:
				// Сложные типы под указателем можно просто присвоить их нулевому значению
				// Например, *[]int можно присвоить nil
				fmt.Fprintf(buf, "\t\trs.%s = nil\n", fieldName)
			default:
				// Fallback для других типов под указателем
				generateNestedPointerReset(buf, fieldName)
			}
			fmt.Fprintf(buf, "\t}\n")
		}
	}
	fmt.Fprintf(buf, "}\n\n")
}

func isPrimitive(typeName string) bool {
	primitives := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true,
		"bool": true, "string": true, "complex64": true, "complex128": true,
		"byte": true, "rune": true,
	}
	return primitives[typeName]
}

func getZeroValue(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return `""`
	default:
		return "0"
	}
}

// generateNestedStructReset генерирует вызов Reset() для невложенной структуры
func generateNestedStructReset(buf *bytes.Buffer, fieldName string) {
	// Для структур, которые могут быть вложенными, мы используем приведение типа к интерфейсу resetable
	// чтобы избежать ошибок компиляции, если метод Reset не существует.
	fmt.Fprintf(buf, "\tif resetter, ok := rs.%s.(resetable); ok {\n", fieldName)
	fmt.Fprintf(buf, "\t\tresetter.Reset()\n")
	fmt.Fprintf(buf, "\t}\n")
}

// generateNestedPointerReset генерирует вызов Reset() для вложенного указателя
func generateNestedPointerReset(buf *bytes.Buffer, fieldName string) {
	// Используем приведение типа для проверки наличия метода Reset()
	fmt.Fprintf(buf, "\t\tif resetter, ok := any(rs.%s).(resetable); ok {\n", fieldName)
	fmt.Fprintf(buf, "\t\t\tresetter.Reset()\n")
	fmt.Fprintf(buf, "\t\t}\n")
}
